language: python
python:
  - "2.7"

install:
  - "pip install ."
  - "pip install -r test-requirements.txt"

# command to run tests
script:
  - |
    if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
      nosetests
    else
      nosetests -a type=unit
    fi
